version: 1.2
workflows:
       -  name: foobar
          subclass: cwl
          primaryDescriptorPath: /Dockstore.cwl
          latestTagAsDefault: true
          testParameterFiles:
              - /dockstore.cwl.json
